services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    branch: main
    pythonVersion: 3.12.0
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: CRYPTOPAY_API_TOKEN
        fromSecret: CRYPTOPAY_API_TOKEN
