services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    branch: main
    type: worker
    pythonVersion: 3.12.0
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: TOKEN_BOTA
      - key: CRYPTOBOT_API_TOKEN
        fromSecret: TOKEN_CRYPTOBOTA
